# Learning PyTorch

In [5]:
import numpy as np

In [1]:
import torch
import torch.nn

In [3]:
data = [[1, 2], [3, 4], [5, 6]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [ ]:
x_ones = torch.ones(x_data.shape, dtype=torch.int64)    # if torch.ones_lihe(x_data) => will directly make new tensor of the size of input tensor  
x_ones

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [12]:
x_rand = torch.rand_like(x_data, dtype=torch.float32)
x_rand

tensor([[0.3679, 0.6790],
        [0.2929, 0.9543],
        [0.3852, 0.9802]])

In [14]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(ones_tensor.shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.1871, 0.8417, 0.3602],
        [0.9717, 0.1296, 0.0198]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [17]:
tensor = torch.rand(3, 4)
print(f"Shape = {tensor.shape}")
print(f"Data type = {tensor.dtype}")
print(f"Device stored on = {tensor.device}")


Shape = torch.Size([3, 4])
Data type = torch.float32
Device stored on = cpu


## Tensor Operations

In [19]:
tensor = torch.ones(4, 4)
print(tensor)
tensor[:1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
t1 = torch.concat([tensor, tensor , tensor], dim = 1)   # concat horizontally, along columns
t1

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
t2 = torch.concat([tensor, tensor, tensor], dim = 0)    # concat vertically, along rows
t2

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
print(tensor)

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
print(tensor.mul(tensor))   # element wise multiplication

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
print(tensor * tensor)      # same as above

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
tensor.matmul(tensor.T)     # matrix multiplication

tensor([[0., 0., 0., 0.],
        [0., 4., 4., 4.],
        [0., 4., 4., 4.],
        [0., 4., 4., 4.]])

In [30]:
tensor.T

tensor([[0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.]])

In [ ]:
tensor @ tensor.T       # same as above

tensor([[0., 0., 0., 0.],
        [0., 4., 4., 4.],
        [0., 4., 4., 4.],
        [0., 4., 4., 4.]])

In [ ]:
tensor.add(5)    # does not change the value of tensor

tensor([[5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [ ]:
tensor + 5      # same as above

tensor([[5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [33]:
tensor

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
tensor.add_(5)      # inplace addition => it will change the value of tensor

tensor([[5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [35]:
tensor

tensor([[5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

- Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [ ]:
t = torch.ones(5)
print(t)

n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [37]:
t.add_(6)
print(t)
print(f"n : {n}")

tensor([7., 7., 7., 7., 7.])
n : [7. 7. 7. 7. 7.]


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [40]:
np.add(n , 1, out = n)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
